/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppHome1 {
    }
    interface AppHome10 {
    }
    interface AppHome100 {
    }
    interface AppHome11 {
    }
    interface AppHome12 {
    }
    interface AppHome13 {
    }
    interface AppHome14 {
    }
    interface AppHome15 {
    }
    interface AppHome16 {
    }
    interface AppHome17 {
    }
    interface AppHome18 {
    }
    interface AppHome19 {
    }
    interface AppHome2 {
    }
    interface AppHome20 {
    }
    interface AppHome21 {
    }
    interface AppHome22 {
    }
    interface AppHome23 {
    }
    interface AppHome24 {
    }
    interface AppHome25 {
    }
    interface AppHome26 {
    }
    interface AppHome27 {
    }
    interface AppHome28 {
    }
    interface AppHome29 {
    }
    interface AppHome3 {
    }
    interface AppHome30 {
    }
    interface AppHome31 {
    }
    interface AppHome32 {
    }
    interface AppHome33 {
    }
    interface AppHome34 {
    }
    interface AppHome35 {
    }
    interface AppHome36 {
    }
    interface AppHome37 {
    }
    interface AppHome38 {
    }
    interface AppHome39 {
    }
    interface AppHome4 {
    }
    interface AppHome40 {
    }
    interface AppHome41 {
    }
    interface AppHome42 {
    }
    interface AppHome43 {
    }
    interface AppHome44 {
    }
    interface AppHome45 {
    }
    interface AppHome46 {
    }
    interface AppHome47 {
    }
    interface AppHome48 {
    }
    interface AppHome49 {
    }
    interface AppHome5 {
    }
    interface AppHome50 {
    }
    interface AppHome51 {
    }
    interface AppHome52 {
    }
    interface AppHome53 {
    }
    interface AppHome54 {
    }
    interface AppHome55 {
    }
    interface AppHome56 {
    }
    interface AppHome57 {
    }
    interface AppHome58 {
    }
    interface AppHome59 {
    }
    interface AppHome6 {
    }
    interface AppHome60 {
    }
    interface AppHome61 {
    }
    interface AppHome62 {
    }
    interface AppHome63 {
    }
    interface AppHome64 {
    }
    interface AppHome65 {
    }
    interface AppHome66 {
    }
    interface AppHome67 {
    }
    interface AppHome68 {
    }
    interface AppHome69 {
    }
    interface AppHome7 {
    }
    interface AppHome70 {
    }
    interface AppHome71 {
    }
    interface AppHome72 {
    }
    interface AppHome73 {
    }
    interface AppHome74 {
    }
    interface AppHome75 {
    }
    interface AppHome76 {
    }
    interface AppHome77 {
    }
    interface AppHome78 {
    }
    interface AppHome79 {
    }
    interface AppHome8 {
    }
    interface AppHome80 {
    }
    interface AppHome81 {
    }
    interface AppHome82 {
    }
    interface AppHome83 {
    }
    interface AppHome84 {
    }
    interface AppHome85 {
    }
    interface AppHome86 {
    }
    interface AppHome87 {
    }
    interface AppHome88 {
    }
    interface AppHome89 {
    }
    interface AppHome9 {
    }
    interface AppHome90 {
    }
    interface AppHome91 {
    }
    interface AppHome92 {
    }
    interface AppHome93 {
    }
    interface AppHome94 {
    }
    interface AppHome95 {
    }
    interface AppHome96 {
    }
    interface AppHome97 {
    }
    interface AppHome98 {
    }
    interface AppHome99 {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppHome1Element extends Components.AppHome1, HTMLStencilElement {
    }
    var HTMLAppHome1Element: {
        prototype: HTMLAppHome1Element;
        new (): HTMLAppHome1Element;
    };
    interface HTMLAppHome10Element extends Components.AppHome10, HTMLStencilElement {
    }
    var HTMLAppHome10Element: {
        prototype: HTMLAppHome10Element;
        new (): HTMLAppHome10Element;
    };
    interface HTMLAppHome100Element extends Components.AppHome100, HTMLStencilElement {
    }
    var HTMLAppHome100Element: {
        prototype: HTMLAppHome100Element;
        new (): HTMLAppHome100Element;
    };
    interface HTMLAppHome11Element extends Components.AppHome11, HTMLStencilElement {
    }
    var HTMLAppHome11Element: {
        prototype: HTMLAppHome11Element;
        new (): HTMLAppHome11Element;
    };
    interface HTMLAppHome12Element extends Components.AppHome12, HTMLStencilElement {
    }
    var HTMLAppHome12Element: {
        prototype: HTMLAppHome12Element;
        new (): HTMLAppHome12Element;
    };
    interface HTMLAppHome13Element extends Components.AppHome13, HTMLStencilElement {
    }
    var HTMLAppHome13Element: {
        prototype: HTMLAppHome13Element;
        new (): HTMLAppHome13Element;
    };
    interface HTMLAppHome14Element extends Components.AppHome14, HTMLStencilElement {
    }
    var HTMLAppHome14Element: {
        prototype: HTMLAppHome14Element;
        new (): HTMLAppHome14Element;
    };
    interface HTMLAppHome15Element extends Components.AppHome15, HTMLStencilElement {
    }
    var HTMLAppHome15Element: {
        prototype: HTMLAppHome15Element;
        new (): HTMLAppHome15Element;
    };
    interface HTMLAppHome16Element extends Components.AppHome16, HTMLStencilElement {
    }
    var HTMLAppHome16Element: {
        prototype: HTMLAppHome16Element;
        new (): HTMLAppHome16Element;
    };
    interface HTMLAppHome17Element extends Components.AppHome17, HTMLStencilElement {
    }
    var HTMLAppHome17Element: {
        prototype: HTMLAppHome17Element;
        new (): HTMLAppHome17Element;
    };
    interface HTMLAppHome18Element extends Components.AppHome18, HTMLStencilElement {
    }
    var HTMLAppHome18Element: {
        prototype: HTMLAppHome18Element;
        new (): HTMLAppHome18Element;
    };
    interface HTMLAppHome19Element extends Components.AppHome19, HTMLStencilElement {
    }
    var HTMLAppHome19Element: {
        prototype: HTMLAppHome19Element;
        new (): HTMLAppHome19Element;
    };
    interface HTMLAppHome2Element extends Components.AppHome2, HTMLStencilElement {
    }
    var HTMLAppHome2Element: {
        prototype: HTMLAppHome2Element;
        new (): HTMLAppHome2Element;
    };
    interface HTMLAppHome20Element extends Components.AppHome20, HTMLStencilElement {
    }
    var HTMLAppHome20Element: {
        prototype: HTMLAppHome20Element;
        new (): HTMLAppHome20Element;
    };
    interface HTMLAppHome21Element extends Components.AppHome21, HTMLStencilElement {
    }
    var HTMLAppHome21Element: {
        prototype: HTMLAppHome21Element;
        new (): HTMLAppHome21Element;
    };
    interface HTMLAppHome22Element extends Components.AppHome22, HTMLStencilElement {
    }
    var HTMLAppHome22Element: {
        prototype: HTMLAppHome22Element;
        new (): HTMLAppHome22Element;
    };
    interface HTMLAppHome23Element extends Components.AppHome23, HTMLStencilElement {
    }
    var HTMLAppHome23Element: {
        prototype: HTMLAppHome23Element;
        new (): HTMLAppHome23Element;
    };
    interface HTMLAppHome24Element extends Components.AppHome24, HTMLStencilElement {
    }
    var HTMLAppHome24Element: {
        prototype: HTMLAppHome24Element;
        new (): HTMLAppHome24Element;
    };
    interface HTMLAppHome25Element extends Components.AppHome25, HTMLStencilElement {
    }
    var HTMLAppHome25Element: {
        prototype: HTMLAppHome25Element;
        new (): HTMLAppHome25Element;
    };
    interface HTMLAppHome26Element extends Components.AppHome26, HTMLStencilElement {
    }
    var HTMLAppHome26Element: {
        prototype: HTMLAppHome26Element;
        new (): HTMLAppHome26Element;
    };
    interface HTMLAppHome27Element extends Components.AppHome27, HTMLStencilElement {
    }
    var HTMLAppHome27Element: {
        prototype: HTMLAppHome27Element;
        new (): HTMLAppHome27Element;
    };
    interface HTMLAppHome28Element extends Components.AppHome28, HTMLStencilElement {
    }
    var HTMLAppHome28Element: {
        prototype: HTMLAppHome28Element;
        new (): HTMLAppHome28Element;
    };
    interface HTMLAppHome29Element extends Components.AppHome29, HTMLStencilElement {
    }
    var HTMLAppHome29Element: {
        prototype: HTMLAppHome29Element;
        new (): HTMLAppHome29Element;
    };
    interface HTMLAppHome3Element extends Components.AppHome3, HTMLStencilElement {
    }
    var HTMLAppHome3Element: {
        prototype: HTMLAppHome3Element;
        new (): HTMLAppHome3Element;
    };
    interface HTMLAppHome30Element extends Components.AppHome30, HTMLStencilElement {
    }
    var HTMLAppHome30Element: {
        prototype: HTMLAppHome30Element;
        new (): HTMLAppHome30Element;
    };
    interface HTMLAppHome31Element extends Components.AppHome31, HTMLStencilElement {
    }
    var HTMLAppHome31Element: {
        prototype: HTMLAppHome31Element;
        new (): HTMLAppHome31Element;
    };
    interface HTMLAppHome32Element extends Components.AppHome32, HTMLStencilElement {
    }
    var HTMLAppHome32Element: {
        prototype: HTMLAppHome32Element;
        new (): HTMLAppHome32Element;
    };
    interface HTMLAppHome33Element extends Components.AppHome33, HTMLStencilElement {
    }
    var HTMLAppHome33Element: {
        prototype: HTMLAppHome33Element;
        new (): HTMLAppHome33Element;
    };
    interface HTMLAppHome34Element extends Components.AppHome34, HTMLStencilElement {
    }
    var HTMLAppHome34Element: {
        prototype: HTMLAppHome34Element;
        new (): HTMLAppHome34Element;
    };
    interface HTMLAppHome35Element extends Components.AppHome35, HTMLStencilElement {
    }
    var HTMLAppHome35Element: {
        prototype: HTMLAppHome35Element;
        new (): HTMLAppHome35Element;
    };
    interface HTMLAppHome36Element extends Components.AppHome36, HTMLStencilElement {
    }
    var HTMLAppHome36Element: {
        prototype: HTMLAppHome36Element;
        new (): HTMLAppHome36Element;
    };
    interface HTMLAppHome37Element extends Components.AppHome37, HTMLStencilElement {
    }
    var HTMLAppHome37Element: {
        prototype: HTMLAppHome37Element;
        new (): HTMLAppHome37Element;
    };
    interface HTMLAppHome38Element extends Components.AppHome38, HTMLStencilElement {
    }
    var HTMLAppHome38Element: {
        prototype: HTMLAppHome38Element;
        new (): HTMLAppHome38Element;
    };
    interface HTMLAppHome39Element extends Components.AppHome39, HTMLStencilElement {
    }
    var HTMLAppHome39Element: {
        prototype: HTMLAppHome39Element;
        new (): HTMLAppHome39Element;
    };
    interface HTMLAppHome4Element extends Components.AppHome4, HTMLStencilElement {
    }
    var HTMLAppHome4Element: {
        prototype: HTMLAppHome4Element;
        new (): HTMLAppHome4Element;
    };
    interface HTMLAppHome40Element extends Components.AppHome40, HTMLStencilElement {
    }
    var HTMLAppHome40Element: {
        prototype: HTMLAppHome40Element;
        new (): HTMLAppHome40Element;
    };
    interface HTMLAppHome41Element extends Components.AppHome41, HTMLStencilElement {
    }
    var HTMLAppHome41Element: {
        prototype: HTMLAppHome41Element;
        new (): HTMLAppHome41Element;
    };
    interface HTMLAppHome42Element extends Components.AppHome42, HTMLStencilElement {
    }
    var HTMLAppHome42Element: {
        prototype: HTMLAppHome42Element;
        new (): HTMLAppHome42Element;
    };
    interface HTMLAppHome43Element extends Components.AppHome43, HTMLStencilElement {
    }
    var HTMLAppHome43Element: {
        prototype: HTMLAppHome43Element;
        new (): HTMLAppHome43Element;
    };
    interface HTMLAppHome44Element extends Components.AppHome44, HTMLStencilElement {
    }
    var HTMLAppHome44Element: {
        prototype: HTMLAppHome44Element;
        new (): HTMLAppHome44Element;
    };
    interface HTMLAppHome45Element extends Components.AppHome45, HTMLStencilElement {
    }
    var HTMLAppHome45Element: {
        prototype: HTMLAppHome45Element;
        new (): HTMLAppHome45Element;
    };
    interface HTMLAppHome46Element extends Components.AppHome46, HTMLStencilElement {
    }
    var HTMLAppHome46Element: {
        prototype: HTMLAppHome46Element;
        new (): HTMLAppHome46Element;
    };
    interface HTMLAppHome47Element extends Components.AppHome47, HTMLStencilElement {
    }
    var HTMLAppHome47Element: {
        prototype: HTMLAppHome47Element;
        new (): HTMLAppHome47Element;
    };
    interface HTMLAppHome48Element extends Components.AppHome48, HTMLStencilElement {
    }
    var HTMLAppHome48Element: {
        prototype: HTMLAppHome48Element;
        new (): HTMLAppHome48Element;
    };
    interface HTMLAppHome49Element extends Components.AppHome49, HTMLStencilElement {
    }
    var HTMLAppHome49Element: {
        prototype: HTMLAppHome49Element;
        new (): HTMLAppHome49Element;
    };
    interface HTMLAppHome5Element extends Components.AppHome5, HTMLStencilElement {
    }
    var HTMLAppHome5Element: {
        prototype: HTMLAppHome5Element;
        new (): HTMLAppHome5Element;
    };
    interface HTMLAppHome50Element extends Components.AppHome50, HTMLStencilElement {
    }
    var HTMLAppHome50Element: {
        prototype: HTMLAppHome50Element;
        new (): HTMLAppHome50Element;
    };
    interface HTMLAppHome51Element extends Components.AppHome51, HTMLStencilElement {
    }
    var HTMLAppHome51Element: {
        prototype: HTMLAppHome51Element;
        new (): HTMLAppHome51Element;
    };
    interface HTMLAppHome52Element extends Components.AppHome52, HTMLStencilElement {
    }
    var HTMLAppHome52Element: {
        prototype: HTMLAppHome52Element;
        new (): HTMLAppHome52Element;
    };
    interface HTMLAppHome53Element extends Components.AppHome53, HTMLStencilElement {
    }
    var HTMLAppHome53Element: {
        prototype: HTMLAppHome53Element;
        new (): HTMLAppHome53Element;
    };
    interface HTMLAppHome54Element extends Components.AppHome54, HTMLStencilElement {
    }
    var HTMLAppHome54Element: {
        prototype: HTMLAppHome54Element;
        new (): HTMLAppHome54Element;
    };
    interface HTMLAppHome55Element extends Components.AppHome55, HTMLStencilElement {
    }
    var HTMLAppHome55Element: {
        prototype: HTMLAppHome55Element;
        new (): HTMLAppHome55Element;
    };
    interface HTMLAppHome56Element extends Components.AppHome56, HTMLStencilElement {
    }
    var HTMLAppHome56Element: {
        prototype: HTMLAppHome56Element;
        new (): HTMLAppHome56Element;
    };
    interface HTMLAppHome57Element extends Components.AppHome57, HTMLStencilElement {
    }
    var HTMLAppHome57Element: {
        prototype: HTMLAppHome57Element;
        new (): HTMLAppHome57Element;
    };
    interface HTMLAppHome58Element extends Components.AppHome58, HTMLStencilElement {
    }
    var HTMLAppHome58Element: {
        prototype: HTMLAppHome58Element;
        new (): HTMLAppHome58Element;
    };
    interface HTMLAppHome59Element extends Components.AppHome59, HTMLStencilElement {
    }
    var HTMLAppHome59Element: {
        prototype: HTMLAppHome59Element;
        new (): HTMLAppHome59Element;
    };
    interface HTMLAppHome6Element extends Components.AppHome6, HTMLStencilElement {
    }
    var HTMLAppHome6Element: {
        prototype: HTMLAppHome6Element;
        new (): HTMLAppHome6Element;
    };
    interface HTMLAppHome60Element extends Components.AppHome60, HTMLStencilElement {
    }
    var HTMLAppHome60Element: {
        prototype: HTMLAppHome60Element;
        new (): HTMLAppHome60Element;
    };
    interface HTMLAppHome61Element extends Components.AppHome61, HTMLStencilElement {
    }
    var HTMLAppHome61Element: {
        prototype: HTMLAppHome61Element;
        new (): HTMLAppHome61Element;
    };
    interface HTMLAppHome62Element extends Components.AppHome62, HTMLStencilElement {
    }
    var HTMLAppHome62Element: {
        prototype: HTMLAppHome62Element;
        new (): HTMLAppHome62Element;
    };
    interface HTMLAppHome63Element extends Components.AppHome63, HTMLStencilElement {
    }
    var HTMLAppHome63Element: {
        prototype: HTMLAppHome63Element;
        new (): HTMLAppHome63Element;
    };
    interface HTMLAppHome64Element extends Components.AppHome64, HTMLStencilElement {
    }
    var HTMLAppHome64Element: {
        prototype: HTMLAppHome64Element;
        new (): HTMLAppHome64Element;
    };
    interface HTMLAppHome65Element extends Components.AppHome65, HTMLStencilElement {
    }
    var HTMLAppHome65Element: {
        prototype: HTMLAppHome65Element;
        new (): HTMLAppHome65Element;
    };
    interface HTMLAppHome66Element extends Components.AppHome66, HTMLStencilElement {
    }
    var HTMLAppHome66Element: {
        prototype: HTMLAppHome66Element;
        new (): HTMLAppHome66Element;
    };
    interface HTMLAppHome67Element extends Components.AppHome67, HTMLStencilElement {
    }
    var HTMLAppHome67Element: {
        prototype: HTMLAppHome67Element;
        new (): HTMLAppHome67Element;
    };
    interface HTMLAppHome68Element extends Components.AppHome68, HTMLStencilElement {
    }
    var HTMLAppHome68Element: {
        prototype: HTMLAppHome68Element;
        new (): HTMLAppHome68Element;
    };
    interface HTMLAppHome69Element extends Components.AppHome69, HTMLStencilElement {
    }
    var HTMLAppHome69Element: {
        prototype: HTMLAppHome69Element;
        new (): HTMLAppHome69Element;
    };
    interface HTMLAppHome7Element extends Components.AppHome7, HTMLStencilElement {
    }
    var HTMLAppHome7Element: {
        prototype: HTMLAppHome7Element;
        new (): HTMLAppHome7Element;
    };
    interface HTMLAppHome70Element extends Components.AppHome70, HTMLStencilElement {
    }
    var HTMLAppHome70Element: {
        prototype: HTMLAppHome70Element;
        new (): HTMLAppHome70Element;
    };
    interface HTMLAppHome71Element extends Components.AppHome71, HTMLStencilElement {
    }
    var HTMLAppHome71Element: {
        prototype: HTMLAppHome71Element;
        new (): HTMLAppHome71Element;
    };
    interface HTMLAppHome72Element extends Components.AppHome72, HTMLStencilElement {
    }
    var HTMLAppHome72Element: {
        prototype: HTMLAppHome72Element;
        new (): HTMLAppHome72Element;
    };
    interface HTMLAppHome73Element extends Components.AppHome73, HTMLStencilElement {
    }
    var HTMLAppHome73Element: {
        prototype: HTMLAppHome73Element;
        new (): HTMLAppHome73Element;
    };
    interface HTMLAppHome74Element extends Components.AppHome74, HTMLStencilElement {
    }
    var HTMLAppHome74Element: {
        prototype: HTMLAppHome74Element;
        new (): HTMLAppHome74Element;
    };
    interface HTMLAppHome75Element extends Components.AppHome75, HTMLStencilElement {
    }
    var HTMLAppHome75Element: {
        prototype: HTMLAppHome75Element;
        new (): HTMLAppHome75Element;
    };
    interface HTMLAppHome76Element extends Components.AppHome76, HTMLStencilElement {
    }
    var HTMLAppHome76Element: {
        prototype: HTMLAppHome76Element;
        new (): HTMLAppHome76Element;
    };
    interface HTMLAppHome77Element extends Components.AppHome77, HTMLStencilElement {
    }
    var HTMLAppHome77Element: {
        prototype: HTMLAppHome77Element;
        new (): HTMLAppHome77Element;
    };
    interface HTMLAppHome78Element extends Components.AppHome78, HTMLStencilElement {
    }
    var HTMLAppHome78Element: {
        prototype: HTMLAppHome78Element;
        new (): HTMLAppHome78Element;
    };
    interface HTMLAppHome79Element extends Components.AppHome79, HTMLStencilElement {
    }
    var HTMLAppHome79Element: {
        prototype: HTMLAppHome79Element;
        new (): HTMLAppHome79Element;
    };
    interface HTMLAppHome8Element extends Components.AppHome8, HTMLStencilElement {
    }
    var HTMLAppHome8Element: {
        prototype: HTMLAppHome8Element;
        new (): HTMLAppHome8Element;
    };
    interface HTMLAppHome80Element extends Components.AppHome80, HTMLStencilElement {
    }
    var HTMLAppHome80Element: {
        prototype: HTMLAppHome80Element;
        new (): HTMLAppHome80Element;
    };
    interface HTMLAppHome81Element extends Components.AppHome81, HTMLStencilElement {
    }
    var HTMLAppHome81Element: {
        prototype: HTMLAppHome81Element;
        new (): HTMLAppHome81Element;
    };
    interface HTMLAppHome82Element extends Components.AppHome82, HTMLStencilElement {
    }
    var HTMLAppHome82Element: {
        prototype: HTMLAppHome82Element;
        new (): HTMLAppHome82Element;
    };
    interface HTMLAppHome83Element extends Components.AppHome83, HTMLStencilElement {
    }
    var HTMLAppHome83Element: {
        prototype: HTMLAppHome83Element;
        new (): HTMLAppHome83Element;
    };
    interface HTMLAppHome84Element extends Components.AppHome84, HTMLStencilElement {
    }
    var HTMLAppHome84Element: {
        prototype: HTMLAppHome84Element;
        new (): HTMLAppHome84Element;
    };
    interface HTMLAppHome85Element extends Components.AppHome85, HTMLStencilElement {
    }
    var HTMLAppHome85Element: {
        prototype: HTMLAppHome85Element;
        new (): HTMLAppHome85Element;
    };
    interface HTMLAppHome86Element extends Components.AppHome86, HTMLStencilElement {
    }
    var HTMLAppHome86Element: {
        prototype: HTMLAppHome86Element;
        new (): HTMLAppHome86Element;
    };
    interface HTMLAppHome87Element extends Components.AppHome87, HTMLStencilElement {
    }
    var HTMLAppHome87Element: {
        prototype: HTMLAppHome87Element;
        new (): HTMLAppHome87Element;
    };
    interface HTMLAppHome88Element extends Components.AppHome88, HTMLStencilElement {
    }
    var HTMLAppHome88Element: {
        prototype: HTMLAppHome88Element;
        new (): HTMLAppHome88Element;
    };
    interface HTMLAppHome89Element extends Components.AppHome89, HTMLStencilElement {
    }
    var HTMLAppHome89Element: {
        prototype: HTMLAppHome89Element;
        new (): HTMLAppHome89Element;
    };
    interface HTMLAppHome9Element extends Components.AppHome9, HTMLStencilElement {
    }
    var HTMLAppHome9Element: {
        prototype: HTMLAppHome9Element;
        new (): HTMLAppHome9Element;
    };
    interface HTMLAppHome90Element extends Components.AppHome90, HTMLStencilElement {
    }
    var HTMLAppHome90Element: {
        prototype: HTMLAppHome90Element;
        new (): HTMLAppHome90Element;
    };
    interface HTMLAppHome91Element extends Components.AppHome91, HTMLStencilElement {
    }
    var HTMLAppHome91Element: {
        prototype: HTMLAppHome91Element;
        new (): HTMLAppHome91Element;
    };
    interface HTMLAppHome92Element extends Components.AppHome92, HTMLStencilElement {
    }
    var HTMLAppHome92Element: {
        prototype: HTMLAppHome92Element;
        new (): HTMLAppHome92Element;
    };
    interface HTMLAppHome93Element extends Components.AppHome93, HTMLStencilElement {
    }
    var HTMLAppHome93Element: {
        prototype: HTMLAppHome93Element;
        new (): HTMLAppHome93Element;
    };
    interface HTMLAppHome94Element extends Components.AppHome94, HTMLStencilElement {
    }
    var HTMLAppHome94Element: {
        prototype: HTMLAppHome94Element;
        new (): HTMLAppHome94Element;
    };
    interface HTMLAppHome95Element extends Components.AppHome95, HTMLStencilElement {
    }
    var HTMLAppHome95Element: {
        prototype: HTMLAppHome95Element;
        new (): HTMLAppHome95Element;
    };
    interface HTMLAppHome96Element extends Components.AppHome96, HTMLStencilElement {
    }
    var HTMLAppHome96Element: {
        prototype: HTMLAppHome96Element;
        new (): HTMLAppHome96Element;
    };
    interface HTMLAppHome97Element extends Components.AppHome97, HTMLStencilElement {
    }
    var HTMLAppHome97Element: {
        prototype: HTMLAppHome97Element;
        new (): HTMLAppHome97Element;
    };
    interface HTMLAppHome98Element extends Components.AppHome98, HTMLStencilElement {
    }
    var HTMLAppHome98Element: {
        prototype: HTMLAppHome98Element;
        new (): HTMLAppHome98Element;
    };
    interface HTMLAppHome99Element extends Components.AppHome99, HTMLStencilElement {
    }
    var HTMLAppHome99Element: {
        prototype: HTMLAppHome99Element;
        new (): HTMLAppHome99Element;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-home-1": HTMLAppHome1Element;
        "app-home-10": HTMLAppHome10Element;
        "app-home-100": HTMLAppHome100Element;
        "app-home-11": HTMLAppHome11Element;
        "app-home-12": HTMLAppHome12Element;
        "app-home-13": HTMLAppHome13Element;
        "app-home-14": HTMLAppHome14Element;
        "app-home-15": HTMLAppHome15Element;
        "app-home-16": HTMLAppHome16Element;
        "app-home-17": HTMLAppHome17Element;
        "app-home-18": HTMLAppHome18Element;
        "app-home-19": HTMLAppHome19Element;
        "app-home-2": HTMLAppHome2Element;
        "app-home-20": HTMLAppHome20Element;
        "app-home-21": HTMLAppHome21Element;
        "app-home-22": HTMLAppHome22Element;
        "app-home-23": HTMLAppHome23Element;
        "app-home-24": HTMLAppHome24Element;
        "app-home-25": HTMLAppHome25Element;
        "app-home-26": HTMLAppHome26Element;
        "app-home-27": HTMLAppHome27Element;
        "app-home-28": HTMLAppHome28Element;
        "app-home-29": HTMLAppHome29Element;
        "app-home-3": HTMLAppHome3Element;
        "app-home-30": HTMLAppHome30Element;
        "app-home-31": HTMLAppHome31Element;
        "app-home-32": HTMLAppHome32Element;
        "app-home-33": HTMLAppHome33Element;
        "app-home-34": HTMLAppHome34Element;
        "app-home-35": HTMLAppHome35Element;
        "app-home-36": HTMLAppHome36Element;
        "app-home-37": HTMLAppHome37Element;
        "app-home-38": HTMLAppHome38Element;
        "app-home-39": HTMLAppHome39Element;
        "app-home-4": HTMLAppHome4Element;
        "app-home-40": HTMLAppHome40Element;
        "app-home-41": HTMLAppHome41Element;
        "app-home-42": HTMLAppHome42Element;
        "app-home-43": HTMLAppHome43Element;
        "app-home-44": HTMLAppHome44Element;
        "app-home-45": HTMLAppHome45Element;
        "app-home-46": HTMLAppHome46Element;
        "app-home-47": HTMLAppHome47Element;
        "app-home-48": HTMLAppHome48Element;
        "app-home-49": HTMLAppHome49Element;
        "app-home-5": HTMLAppHome5Element;
        "app-home-50": HTMLAppHome50Element;
        "app-home-51": HTMLAppHome51Element;
        "app-home-52": HTMLAppHome52Element;
        "app-home-53": HTMLAppHome53Element;
        "app-home-54": HTMLAppHome54Element;
        "app-home-55": HTMLAppHome55Element;
        "app-home-56": HTMLAppHome56Element;
        "app-home-57": HTMLAppHome57Element;
        "app-home-58": HTMLAppHome58Element;
        "app-home-59": HTMLAppHome59Element;
        "app-home-6": HTMLAppHome6Element;
        "app-home-60": HTMLAppHome60Element;
        "app-home-61": HTMLAppHome61Element;
        "app-home-62": HTMLAppHome62Element;
        "app-home-63": HTMLAppHome63Element;
        "app-home-64": HTMLAppHome64Element;
        "app-home-65": HTMLAppHome65Element;
        "app-home-66": HTMLAppHome66Element;
        "app-home-67": HTMLAppHome67Element;
        "app-home-68": HTMLAppHome68Element;
        "app-home-69": HTMLAppHome69Element;
        "app-home-7": HTMLAppHome7Element;
        "app-home-70": HTMLAppHome70Element;
        "app-home-71": HTMLAppHome71Element;
        "app-home-72": HTMLAppHome72Element;
        "app-home-73": HTMLAppHome73Element;
        "app-home-74": HTMLAppHome74Element;
        "app-home-75": HTMLAppHome75Element;
        "app-home-76": HTMLAppHome76Element;
        "app-home-77": HTMLAppHome77Element;
        "app-home-78": HTMLAppHome78Element;
        "app-home-79": HTMLAppHome79Element;
        "app-home-8": HTMLAppHome8Element;
        "app-home-80": HTMLAppHome80Element;
        "app-home-81": HTMLAppHome81Element;
        "app-home-82": HTMLAppHome82Element;
        "app-home-83": HTMLAppHome83Element;
        "app-home-84": HTMLAppHome84Element;
        "app-home-85": HTMLAppHome85Element;
        "app-home-86": HTMLAppHome86Element;
        "app-home-87": HTMLAppHome87Element;
        "app-home-88": HTMLAppHome88Element;
        "app-home-89": HTMLAppHome89Element;
        "app-home-9": HTMLAppHome9Element;
        "app-home-90": HTMLAppHome90Element;
        "app-home-91": HTMLAppHome91Element;
        "app-home-92": HTMLAppHome92Element;
        "app-home-93": HTMLAppHome93Element;
        "app-home-94": HTMLAppHome94Element;
        "app-home-95": HTMLAppHome95Element;
        "app-home-96": HTMLAppHome96Element;
        "app-home-97": HTMLAppHome97Element;
        "app-home-98": HTMLAppHome98Element;
        "app-home-99": HTMLAppHome99Element;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppHome1 {
    }
    interface AppHome10 {
    }
    interface AppHome100 {
    }
    interface AppHome11 {
    }
    interface AppHome12 {
    }
    interface AppHome13 {
    }
    interface AppHome14 {
    }
    interface AppHome15 {
    }
    interface AppHome16 {
    }
    interface AppHome17 {
    }
    interface AppHome18 {
    }
    interface AppHome19 {
    }
    interface AppHome2 {
    }
    interface AppHome20 {
    }
    interface AppHome21 {
    }
    interface AppHome22 {
    }
    interface AppHome23 {
    }
    interface AppHome24 {
    }
    interface AppHome25 {
    }
    interface AppHome26 {
    }
    interface AppHome27 {
    }
    interface AppHome28 {
    }
    interface AppHome29 {
    }
    interface AppHome3 {
    }
    interface AppHome30 {
    }
    interface AppHome31 {
    }
    interface AppHome32 {
    }
    interface AppHome33 {
    }
    interface AppHome34 {
    }
    interface AppHome35 {
    }
    interface AppHome36 {
    }
    interface AppHome37 {
    }
    interface AppHome38 {
    }
    interface AppHome39 {
    }
    interface AppHome4 {
    }
    interface AppHome40 {
    }
    interface AppHome41 {
    }
    interface AppHome42 {
    }
    interface AppHome43 {
    }
    interface AppHome44 {
    }
    interface AppHome45 {
    }
    interface AppHome46 {
    }
    interface AppHome47 {
    }
    interface AppHome48 {
    }
    interface AppHome49 {
    }
    interface AppHome5 {
    }
    interface AppHome50 {
    }
    interface AppHome51 {
    }
    interface AppHome52 {
    }
    interface AppHome53 {
    }
    interface AppHome54 {
    }
    interface AppHome55 {
    }
    interface AppHome56 {
    }
    interface AppHome57 {
    }
    interface AppHome58 {
    }
    interface AppHome59 {
    }
    interface AppHome6 {
    }
    interface AppHome60 {
    }
    interface AppHome61 {
    }
    interface AppHome62 {
    }
    interface AppHome63 {
    }
    interface AppHome64 {
    }
    interface AppHome65 {
    }
    interface AppHome66 {
    }
    interface AppHome67 {
    }
    interface AppHome68 {
    }
    interface AppHome69 {
    }
    interface AppHome7 {
    }
    interface AppHome70 {
    }
    interface AppHome71 {
    }
    interface AppHome72 {
    }
    interface AppHome73 {
    }
    interface AppHome74 {
    }
    interface AppHome75 {
    }
    interface AppHome76 {
    }
    interface AppHome77 {
    }
    interface AppHome78 {
    }
    interface AppHome79 {
    }
    interface AppHome8 {
    }
    interface AppHome80 {
    }
    interface AppHome81 {
    }
    interface AppHome82 {
    }
    interface AppHome83 {
    }
    interface AppHome84 {
    }
    interface AppHome85 {
    }
    interface AppHome86 {
    }
    interface AppHome87 {
    }
    interface AppHome88 {
    }
    interface AppHome89 {
    }
    interface AppHome9 {
    }
    interface AppHome90 {
    }
    interface AppHome91 {
    }
    interface AppHome92 {
    }
    interface AppHome93 {
    }
    interface AppHome94 {
    }
    interface AppHome95 {
    }
    interface AppHome96 {
    }
    interface AppHome97 {
    }
    interface AppHome98 {
    }
    interface AppHome99 {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-home-1": AppHome1;
        "app-home-10": AppHome10;
        "app-home-100": AppHome100;
        "app-home-11": AppHome11;
        "app-home-12": AppHome12;
        "app-home-13": AppHome13;
        "app-home-14": AppHome14;
        "app-home-15": AppHome15;
        "app-home-16": AppHome16;
        "app-home-17": AppHome17;
        "app-home-18": AppHome18;
        "app-home-19": AppHome19;
        "app-home-2": AppHome2;
        "app-home-20": AppHome20;
        "app-home-21": AppHome21;
        "app-home-22": AppHome22;
        "app-home-23": AppHome23;
        "app-home-24": AppHome24;
        "app-home-25": AppHome25;
        "app-home-26": AppHome26;
        "app-home-27": AppHome27;
        "app-home-28": AppHome28;
        "app-home-29": AppHome29;
        "app-home-3": AppHome3;
        "app-home-30": AppHome30;
        "app-home-31": AppHome31;
        "app-home-32": AppHome32;
        "app-home-33": AppHome33;
        "app-home-34": AppHome34;
        "app-home-35": AppHome35;
        "app-home-36": AppHome36;
        "app-home-37": AppHome37;
        "app-home-38": AppHome38;
        "app-home-39": AppHome39;
        "app-home-4": AppHome4;
        "app-home-40": AppHome40;
        "app-home-41": AppHome41;
        "app-home-42": AppHome42;
        "app-home-43": AppHome43;
        "app-home-44": AppHome44;
        "app-home-45": AppHome45;
        "app-home-46": AppHome46;
        "app-home-47": AppHome47;
        "app-home-48": AppHome48;
        "app-home-49": AppHome49;
        "app-home-5": AppHome5;
        "app-home-50": AppHome50;
        "app-home-51": AppHome51;
        "app-home-52": AppHome52;
        "app-home-53": AppHome53;
        "app-home-54": AppHome54;
        "app-home-55": AppHome55;
        "app-home-56": AppHome56;
        "app-home-57": AppHome57;
        "app-home-58": AppHome58;
        "app-home-59": AppHome59;
        "app-home-6": AppHome6;
        "app-home-60": AppHome60;
        "app-home-61": AppHome61;
        "app-home-62": AppHome62;
        "app-home-63": AppHome63;
        "app-home-64": AppHome64;
        "app-home-65": AppHome65;
        "app-home-66": AppHome66;
        "app-home-67": AppHome67;
        "app-home-68": AppHome68;
        "app-home-69": AppHome69;
        "app-home-7": AppHome7;
        "app-home-70": AppHome70;
        "app-home-71": AppHome71;
        "app-home-72": AppHome72;
        "app-home-73": AppHome73;
        "app-home-74": AppHome74;
        "app-home-75": AppHome75;
        "app-home-76": AppHome76;
        "app-home-77": AppHome77;
        "app-home-78": AppHome78;
        "app-home-79": AppHome79;
        "app-home-8": AppHome8;
        "app-home-80": AppHome80;
        "app-home-81": AppHome81;
        "app-home-82": AppHome82;
        "app-home-83": AppHome83;
        "app-home-84": AppHome84;
        "app-home-85": AppHome85;
        "app-home-86": AppHome86;
        "app-home-87": AppHome87;
        "app-home-88": AppHome88;
        "app-home-89": AppHome89;
        "app-home-9": AppHome9;
        "app-home-90": AppHome90;
        "app-home-91": AppHome91;
        "app-home-92": AppHome92;
        "app-home-93": AppHome93;
        "app-home-94": AppHome94;
        "app-home-95": AppHome95;
        "app-home-96": AppHome96;
        "app-home-97": AppHome97;
        "app-home-98": AppHome98;
        "app-home-99": AppHome99;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-home-1": LocalJSX.AppHome1 & JSXBase.HTMLAttributes<HTMLAppHome1Element>;
            "app-home-10": LocalJSX.AppHome10 & JSXBase.HTMLAttributes<HTMLAppHome10Element>;
            "app-home-100": LocalJSX.AppHome100 & JSXBase.HTMLAttributes<HTMLAppHome100Element>;
            "app-home-11": LocalJSX.AppHome11 & JSXBase.HTMLAttributes<HTMLAppHome11Element>;
            "app-home-12": LocalJSX.AppHome12 & JSXBase.HTMLAttributes<HTMLAppHome12Element>;
            "app-home-13": LocalJSX.AppHome13 & JSXBase.HTMLAttributes<HTMLAppHome13Element>;
            "app-home-14": LocalJSX.AppHome14 & JSXBase.HTMLAttributes<HTMLAppHome14Element>;
            "app-home-15": LocalJSX.AppHome15 & JSXBase.HTMLAttributes<HTMLAppHome15Element>;
            "app-home-16": LocalJSX.AppHome16 & JSXBase.HTMLAttributes<HTMLAppHome16Element>;
            "app-home-17": LocalJSX.AppHome17 & JSXBase.HTMLAttributes<HTMLAppHome17Element>;
            "app-home-18": LocalJSX.AppHome18 & JSXBase.HTMLAttributes<HTMLAppHome18Element>;
            "app-home-19": LocalJSX.AppHome19 & JSXBase.HTMLAttributes<HTMLAppHome19Element>;
            "app-home-2": LocalJSX.AppHome2 & JSXBase.HTMLAttributes<HTMLAppHome2Element>;
            "app-home-20": LocalJSX.AppHome20 & JSXBase.HTMLAttributes<HTMLAppHome20Element>;
            "app-home-21": LocalJSX.AppHome21 & JSXBase.HTMLAttributes<HTMLAppHome21Element>;
            "app-home-22": LocalJSX.AppHome22 & JSXBase.HTMLAttributes<HTMLAppHome22Element>;
            "app-home-23": LocalJSX.AppHome23 & JSXBase.HTMLAttributes<HTMLAppHome23Element>;
            "app-home-24": LocalJSX.AppHome24 & JSXBase.HTMLAttributes<HTMLAppHome24Element>;
            "app-home-25": LocalJSX.AppHome25 & JSXBase.HTMLAttributes<HTMLAppHome25Element>;
            "app-home-26": LocalJSX.AppHome26 & JSXBase.HTMLAttributes<HTMLAppHome26Element>;
            "app-home-27": LocalJSX.AppHome27 & JSXBase.HTMLAttributes<HTMLAppHome27Element>;
            "app-home-28": LocalJSX.AppHome28 & JSXBase.HTMLAttributes<HTMLAppHome28Element>;
            "app-home-29": LocalJSX.AppHome29 & JSXBase.HTMLAttributes<HTMLAppHome29Element>;
            "app-home-3": LocalJSX.AppHome3 & JSXBase.HTMLAttributes<HTMLAppHome3Element>;
            "app-home-30": LocalJSX.AppHome30 & JSXBase.HTMLAttributes<HTMLAppHome30Element>;
            "app-home-31": LocalJSX.AppHome31 & JSXBase.HTMLAttributes<HTMLAppHome31Element>;
            "app-home-32": LocalJSX.AppHome32 & JSXBase.HTMLAttributes<HTMLAppHome32Element>;
            "app-home-33": LocalJSX.AppHome33 & JSXBase.HTMLAttributes<HTMLAppHome33Element>;
            "app-home-34": LocalJSX.AppHome34 & JSXBase.HTMLAttributes<HTMLAppHome34Element>;
            "app-home-35": LocalJSX.AppHome35 & JSXBase.HTMLAttributes<HTMLAppHome35Element>;
            "app-home-36": LocalJSX.AppHome36 & JSXBase.HTMLAttributes<HTMLAppHome36Element>;
            "app-home-37": LocalJSX.AppHome37 & JSXBase.HTMLAttributes<HTMLAppHome37Element>;
            "app-home-38": LocalJSX.AppHome38 & JSXBase.HTMLAttributes<HTMLAppHome38Element>;
            "app-home-39": LocalJSX.AppHome39 & JSXBase.HTMLAttributes<HTMLAppHome39Element>;
            "app-home-4": LocalJSX.AppHome4 & JSXBase.HTMLAttributes<HTMLAppHome4Element>;
            "app-home-40": LocalJSX.AppHome40 & JSXBase.HTMLAttributes<HTMLAppHome40Element>;
            "app-home-41": LocalJSX.AppHome41 & JSXBase.HTMLAttributes<HTMLAppHome41Element>;
            "app-home-42": LocalJSX.AppHome42 & JSXBase.HTMLAttributes<HTMLAppHome42Element>;
            "app-home-43": LocalJSX.AppHome43 & JSXBase.HTMLAttributes<HTMLAppHome43Element>;
            "app-home-44": LocalJSX.AppHome44 & JSXBase.HTMLAttributes<HTMLAppHome44Element>;
            "app-home-45": LocalJSX.AppHome45 & JSXBase.HTMLAttributes<HTMLAppHome45Element>;
            "app-home-46": LocalJSX.AppHome46 & JSXBase.HTMLAttributes<HTMLAppHome46Element>;
            "app-home-47": LocalJSX.AppHome47 & JSXBase.HTMLAttributes<HTMLAppHome47Element>;
            "app-home-48": LocalJSX.AppHome48 & JSXBase.HTMLAttributes<HTMLAppHome48Element>;
            "app-home-49": LocalJSX.AppHome49 & JSXBase.HTMLAttributes<HTMLAppHome49Element>;
            "app-home-5": LocalJSX.AppHome5 & JSXBase.HTMLAttributes<HTMLAppHome5Element>;
            "app-home-50": LocalJSX.AppHome50 & JSXBase.HTMLAttributes<HTMLAppHome50Element>;
            "app-home-51": LocalJSX.AppHome51 & JSXBase.HTMLAttributes<HTMLAppHome51Element>;
            "app-home-52": LocalJSX.AppHome52 & JSXBase.HTMLAttributes<HTMLAppHome52Element>;
            "app-home-53": LocalJSX.AppHome53 & JSXBase.HTMLAttributes<HTMLAppHome53Element>;
            "app-home-54": LocalJSX.AppHome54 & JSXBase.HTMLAttributes<HTMLAppHome54Element>;
            "app-home-55": LocalJSX.AppHome55 & JSXBase.HTMLAttributes<HTMLAppHome55Element>;
            "app-home-56": LocalJSX.AppHome56 & JSXBase.HTMLAttributes<HTMLAppHome56Element>;
            "app-home-57": LocalJSX.AppHome57 & JSXBase.HTMLAttributes<HTMLAppHome57Element>;
            "app-home-58": LocalJSX.AppHome58 & JSXBase.HTMLAttributes<HTMLAppHome58Element>;
            "app-home-59": LocalJSX.AppHome59 & JSXBase.HTMLAttributes<HTMLAppHome59Element>;
            "app-home-6": LocalJSX.AppHome6 & JSXBase.HTMLAttributes<HTMLAppHome6Element>;
            "app-home-60": LocalJSX.AppHome60 & JSXBase.HTMLAttributes<HTMLAppHome60Element>;
            "app-home-61": LocalJSX.AppHome61 & JSXBase.HTMLAttributes<HTMLAppHome61Element>;
            "app-home-62": LocalJSX.AppHome62 & JSXBase.HTMLAttributes<HTMLAppHome62Element>;
            "app-home-63": LocalJSX.AppHome63 & JSXBase.HTMLAttributes<HTMLAppHome63Element>;
            "app-home-64": LocalJSX.AppHome64 & JSXBase.HTMLAttributes<HTMLAppHome64Element>;
            "app-home-65": LocalJSX.AppHome65 & JSXBase.HTMLAttributes<HTMLAppHome65Element>;
            "app-home-66": LocalJSX.AppHome66 & JSXBase.HTMLAttributes<HTMLAppHome66Element>;
            "app-home-67": LocalJSX.AppHome67 & JSXBase.HTMLAttributes<HTMLAppHome67Element>;
            "app-home-68": LocalJSX.AppHome68 & JSXBase.HTMLAttributes<HTMLAppHome68Element>;
            "app-home-69": LocalJSX.AppHome69 & JSXBase.HTMLAttributes<HTMLAppHome69Element>;
            "app-home-7": LocalJSX.AppHome7 & JSXBase.HTMLAttributes<HTMLAppHome7Element>;
            "app-home-70": LocalJSX.AppHome70 & JSXBase.HTMLAttributes<HTMLAppHome70Element>;
            "app-home-71": LocalJSX.AppHome71 & JSXBase.HTMLAttributes<HTMLAppHome71Element>;
            "app-home-72": LocalJSX.AppHome72 & JSXBase.HTMLAttributes<HTMLAppHome72Element>;
            "app-home-73": LocalJSX.AppHome73 & JSXBase.HTMLAttributes<HTMLAppHome73Element>;
            "app-home-74": LocalJSX.AppHome74 & JSXBase.HTMLAttributes<HTMLAppHome74Element>;
            "app-home-75": LocalJSX.AppHome75 & JSXBase.HTMLAttributes<HTMLAppHome75Element>;
            "app-home-76": LocalJSX.AppHome76 & JSXBase.HTMLAttributes<HTMLAppHome76Element>;
            "app-home-77": LocalJSX.AppHome77 & JSXBase.HTMLAttributes<HTMLAppHome77Element>;
            "app-home-78": LocalJSX.AppHome78 & JSXBase.HTMLAttributes<HTMLAppHome78Element>;
            "app-home-79": LocalJSX.AppHome79 & JSXBase.HTMLAttributes<HTMLAppHome79Element>;
            "app-home-8": LocalJSX.AppHome8 & JSXBase.HTMLAttributes<HTMLAppHome8Element>;
            "app-home-80": LocalJSX.AppHome80 & JSXBase.HTMLAttributes<HTMLAppHome80Element>;
            "app-home-81": LocalJSX.AppHome81 & JSXBase.HTMLAttributes<HTMLAppHome81Element>;
            "app-home-82": LocalJSX.AppHome82 & JSXBase.HTMLAttributes<HTMLAppHome82Element>;
            "app-home-83": LocalJSX.AppHome83 & JSXBase.HTMLAttributes<HTMLAppHome83Element>;
            "app-home-84": LocalJSX.AppHome84 & JSXBase.HTMLAttributes<HTMLAppHome84Element>;
            "app-home-85": LocalJSX.AppHome85 & JSXBase.HTMLAttributes<HTMLAppHome85Element>;
            "app-home-86": LocalJSX.AppHome86 & JSXBase.HTMLAttributes<HTMLAppHome86Element>;
            "app-home-87": LocalJSX.AppHome87 & JSXBase.HTMLAttributes<HTMLAppHome87Element>;
            "app-home-88": LocalJSX.AppHome88 & JSXBase.HTMLAttributes<HTMLAppHome88Element>;
            "app-home-89": LocalJSX.AppHome89 & JSXBase.HTMLAttributes<HTMLAppHome89Element>;
            "app-home-9": LocalJSX.AppHome9 & JSXBase.HTMLAttributes<HTMLAppHome9Element>;
            "app-home-90": LocalJSX.AppHome90 & JSXBase.HTMLAttributes<HTMLAppHome90Element>;
            "app-home-91": LocalJSX.AppHome91 & JSXBase.HTMLAttributes<HTMLAppHome91Element>;
            "app-home-92": LocalJSX.AppHome92 & JSXBase.HTMLAttributes<HTMLAppHome92Element>;
            "app-home-93": LocalJSX.AppHome93 & JSXBase.HTMLAttributes<HTMLAppHome93Element>;
            "app-home-94": LocalJSX.AppHome94 & JSXBase.HTMLAttributes<HTMLAppHome94Element>;
            "app-home-95": LocalJSX.AppHome95 & JSXBase.HTMLAttributes<HTMLAppHome95Element>;
            "app-home-96": LocalJSX.AppHome96 & JSXBase.HTMLAttributes<HTMLAppHome96Element>;
            "app-home-97": LocalJSX.AppHome97 & JSXBase.HTMLAttributes<HTMLAppHome97Element>;
            "app-home-98": LocalJSX.AppHome98 & JSXBase.HTMLAttributes<HTMLAppHome98Element>;
            "app-home-99": LocalJSX.AppHome99 & JSXBase.HTMLAttributes<HTMLAppHome99Element>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
